### ISSUE TITLE
靴下の部位について

### ISSUE THREAD

**Issue by ShTair** [koala31/MiracleNikkiJp_items#82]
靴下ですが、
レッグウォーマーみたいな、靴下と同時に装着可能なものがありますが、どのように登録しましょう？

参考にしているサイトでは「+α」って書いてあったので、
とりあえず「靴下+α」にしてみました。
https://github.com/ShTair/MiracleNikkiJp_items/commit/0e88d69e6718368b509b513d1655bc6c50e67a50

**Comment by koala31** [comment]
靴下・ガーター
が第一候補です。種類は、なるべく物の名前や部位の名前にしたいという思いがあります。(外れる物もでてしまうのですが)
対象のアイテムは、ガーターに類するものが多いように思うので靴下・ガーターでいかがでしょう。
靴下の中で同時に使えるアイテムの存在を見逃していました。
いつもありがとうございます。

種類の追加となるので、2行目のFormatVersionを+1して、89907-89930をずらしつつ89907に新種を記述する作業を予定しています。

**Comment by ShTair** [comment]
> なるべく物の名前や部位の名前にしたい

なるほど、了解です。
靴下・ガーターに修正しておきます。
