### ISSUE TITLE
アプリバージョンupに伴う種類の変更について

### ISSUE THREAD

**Issue by koala31** [koala31/MiracleNikkiJp_items#90]
このデータも追従した方が良いと思うのですが、ご意見あれば。ここでも、Twitterでも。

**Comment by ShTair** [comment]
正しい分類名を公式に教えてくれたわけなので、
折角なのでゲームに合わせるのがいいと思います。

~~靴下も分類分けしてくれ…！~~

**Comment by koala31** [comment]
そうですよね。
FormatVersion 5 を予定します。
コメントありがとうございます!

**Comment by koala31** [comment]
アクセサリーについて、以下の変更を予定しています。
コメントに 新設？ と書いた所は、私がアイテムを持っていないところで、未確認のところです。
特殊 だけは、「特殊・フェイス」か、単に「フェイス」か迷うところです。いっそ単純でも良いなぁ。

|FormatVersion 4|FormatVersion 5|コメント|
|:--:|:--:|:--|
|ヘアアクセサリー|ヘッドアクセ||
|ヘアアクセ・ベール|ヴェール||
|ヘアアクセ・追加|カチューシャ||
|－|つけ耳|新設？|
|耳飾り|耳飾り||
|首飾り・ストール|マフラー||
|首飾り|ネックレス||
|腕飾り・右手|右手飾り||
|腕飾り・左手|左手飾り||
|腕飾り・手袋両手物|手袋||
|手持品・右手|右手持ち|両手持ちと排他なので注意|
|手持品・左手|左手持ち|両手持ちと排他なので注意|
|－|両手持ち|該当品：六番目の契約書|
|腰飾り|腰飾り||
|特殊・眼鏡|フェイス||
|特殊・肩掛け|ボディ||
|特殊・タトゥ|タトゥー||
|特殊・羽|羽根||
|特殊・しっぽ|しっぽ||
|特殊・落物吊物吐息|前景||
|特殊・マスコット|後景||
|－|吊り|新設？|
|特殊・敷物|床||
|－|肌|新設？|
|特殊・運命の箱|？|運命の箱を所有していないので何処へ行ったか未確認|
|特殊・予備|－|将来拡張用でしたが今後は不要かな|

**Comment by ShTair** [comment]
運命の箱、新設の吊りか肌のどちらかのはずなので…どちらかといえば吊りなのかなぁ…
持ってないのがどれに当たるのか、まず判明させるのがいいかもですね。どこかに情報ないかなー

「特殊・フェイス」にするか「フェイス」にするか、難しいところですね。
「特殊・」とか「所持品・」とかついてた方が、このアイテム表を使うプログラムを作るときに処理しやすいのかな、とも思いましたが、
対応表作ればいいだけだし、人間が見る分にはどれがどれだかすぐわかるので、「フェイス」だけでいいかも？と思いました。
どのみち両手持ちが片手持ちと排他だ、みたいなのを示す別の表はいりますしね。

**Comment by koala31** [comment]
Twitterで教えてもらえました。

|FormatVersion 4|FormatVersion 5|
|:--:|:--:|
|特殊・運命の箱|吊り|

です。
特殊の「フェイス」は単に「フェイス」で行こうと思っています。

**Comment by koala31** [comment]
変更方針について、Wikiに記載しました。  
[アクセサリーの分類変更](https://github.com/koala31/MiracleNikkiJp_items/wiki/%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B5%E3%83%AA%E3%83%BC%E3%81%AE%E5%88%86%E9%A1%9E%E5%A4%89%E6%9B%B4)

**Comment by koala31** [comment]
プルリクエスト #91 発行しました。
明日の夜にでもマージしたいと思います。

**Comment by koala31** [comment]
マージしました。チェック＆コメントありがとうございました。
